### ISSUE TITLE
首页预览时 无法正常显示

### ISSUE THREAD

**Issue by wgx-dh** [YunYouJun/hexo-tag-common#2]
![image](https://user-images.githubusercontent.com/63238251/142586445-fb6d4225-346e-4f97-b1d2-4890eefb24cf.png)
![image](https://user-images.githubusercontent.com/63238251/142586626-081f6b04-c1c7-4f33-b9a9-e8f1a9ae2931.png)
点进去 可以正常显示
![image](https://user-images.githubusercontent.com/63238251/142586760-71c6f4b8-5bca-489d-b828-8aa22990eb08.png)

**Comment by wgx-dh** [comment]
1.7.0  主题版本

**Comment by YunYouJun** [comment]
已 Release v0.0.4，添加了自定义布局 `layout `功能。

如需在首页显示，则设置为

```yaml
tag_common:
  cdn: true # enable jsdelivr CDN, default is true
  # which layout to use
  # more info see https://hexo.io/api/injector.html#to-lt-string-gt
  layout:
    - post
    - page
    - home
```
